# This is a basic workflow to help you get started with Actions

name: fetch-convert-filter-upload

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch-convert-filter-upload:
    # The type of runner that the job will run on
    runs-on: ssubbotin/osmium-tool
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: bash fetch-convert-filter-upload.sh
