# This is a basic workflow to help you get started with Actions

name: fetch-convert-filter-upload

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fetch-convert-filter-upload:
    # The type of runner that the job will run on
    #runs-on: ssubbotin/osmium-tool
    runs-on: ubuntu-22.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install packages
        run: sudo apt install -y pbzip2 rclone osmium-tool
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Config for rclone
        run: echo $RCLONE_CONF > rclone.conf

      # Run it all!
      - name: Run a one-line script
        run: bash process-all.sh
